services:
  - type: web
    name: quiz-generator-api
    runtime: python
    rootDir: ai_quiz_generator/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.4
